import { supabase } from './supabase'

// Counter-sign tokens for the "They Sign" flow on the Export Agreement page.
// See supabase/schema.sql → public.agreement_signatures for the table layout.

export interface AgreementSignature {
  id: string                              // uuid — used in the public /sign/:token URL
  project_id: string
  user_id: string | null                  // null when generated by an unauthenticated drafter
  project_name: string
  status: 'pending' | 'signed'
  counter_signer_name: string
  counter_signer_signature: string        // base64 PNG data URL, set on submit
  counter_signed_at: string | null
  viewed_pdf_at: string | null
  created_at: string
}

/**
 * Drafter creates a fresh token for a project. Returns the new row so the
 * caller can immediately render the QR code + URL without a round-trip.
 *
 * Being signed in is *not* required — the token uuid in the URL is the bearer
 * credential, so an unauthenticated drafter can still generate a link. When a
 * user is present we stamp `user_id` so they keep ownership of the token.
 */
export async function createSignatureToken(args: {
  projectId: string
  projectName: string
}): Promise<AgreementSignature | null> {
  const { data: { user } } = await supabase.auth.getUser()

  const { data, error } = await supabase
    .from('agreement_signatures')
    .insert({
      project_id:   args.projectId,
      user_id:      user?.id ?? null,
      project_name: args.projectName,
      status:       'pending',
    })
    .select()
    .single()

  if (error) {
    console.error('[exports] createSignatureToken failed:', error)
    return null
  }
  return data as AgreementSignature
}

/**
 * List tokens for a project so the drafter can see pending / completed
 * counter-signs (and surface the latest one in the UI).
 *
 * This is a direct table select, so it only returns rows the caller owns via
 * the "Drafter manages own agreement signatures" RLS policy (auth.uid() =
 * user_id). That's the only real path: a project must be saved to back a token,
 * and saving requires sign-in — so every backend token has an authenticated
 * owner. (The demo project never reaches here; its tokens are minted client-side
 * in CounterSignPanel.) An unauthenticated caller gets an empty list, which is
 * fine because anonymous drafting can't produce a persisted token anyway.
 */
export async function listSignatureTokens(projectId: string): Promise<AgreementSignature[]> {
  const { data, error } = await supabase
    .from('agreement_signatures')
    .select('*')
    .eq('project_id', projectId)
    .order('created_at', { ascending: false })

  if (error) {
    console.error('[exports] listSignatureTokens failed:', error)
    return []
  }
  return (data ?? []) as AgreementSignature[]
}

/**
 * Public lookup by token — used by the /sign/:token page. No auth required;
 * the token in the URL is the bearer credential. The table has no public select
 * policy (that would let anyone dump every row), so the read goes through the
 * token-gated get_agreement_signature RPC — you only get a row if you already
 * hold its uuid.
 */
export async function getSignatureToken(token: string): Promise<AgreementSignature | null> {
  const { data, error } = await supabase.rpc('get_agreement_signature', { sig_token: token })

  if (error) {
    // Includes malformed (non-uuid) tokens — surface as "not found".
    console.error('[exports] getSignatureToken failed:', error)
    return null
  }
  const row = Array.isArray(data) ? data[0] : data
  return (row as AgreementSignature) ?? null
}

/**
 * Mark the moment the counter-signer opened the PDF. Unlocks the signature
 * pad client-side so they can't sign without reviewing the document.
 */
export async function markPdfViewed(token: string): Promise<boolean> {
  // Goes through a column-locked SECURITY DEFINER RPC: the table has no public
  // update policy, so this can only ever touch viewed_pdf_at on a pending row.
  const { error } = await supabase.rpc('mark_agreement_pdf_viewed', { sig_token: token })

  if (error) {
    console.error('[exports] markPdfViewed failed:', error)
    return false
  }
  return true
}

/**
 * Counter-signer submits their name + signature image. Flips status to
 * 'signed' which the RLS policy then locks against further writes.
 */
export async function submitCounterSignature(args: {
  token:     string
  name:      string
  signature: string
}): Promise<boolean> {
  // Column-locked SECURITY DEFINER RPC: only the counter-signer fields + status
  // can change, and only while the row is still pending — so the table needs no
  // public update policy and a token can be used exactly once.
  const { error } = await supabase.rpc('submit_agreement_counter_signature', {
    sig_token:        args.token,
    signer_name:      args.name,
    signer_signature: args.signature,
  })

  if (error) {
    console.error('[exports] submitCounterSignature failed:', error)
    return false
  }
  return true
}
